### ISSUE TITLE
DCTL failed with error C2679 when build by msvc on Windows

### ISSUE THREAD

**Issue by QuellaZhang** [rhalbersma/dctl#25]
DCTL failed with error C2679 when build by msvc on Windows, I use latest version 2ee0699 on master branch. Could you please help take a look at this? Noted that this issue only found when compiles with unreleased vctoolset, that next release of MSVC will have this behavior.

**You can repro this issue as the steps below:**

1. git clone https://github.com/rhalbersma/dctl.git D:\DCTL\src
2. git clone https://github.com/rhalbersma/xstd.git D:\DCTL\xstd
3. git clone https://github.com/rhalbersma/int_set.git D:\DCTL\int_set
4. extract boost_1_67_0.zip to D:\DCTL\boost_1_67_0\x64
5. open a VS 2017 amd64 command prompt as admin and browse to D:\DCTL
6. cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 -DBOOST_ROOT=D:\DCTL\boost_1_67_0\x64\boost -DBOOST_INCLUDEDIR=D:\DCTL\boost_1_67_0\x64 ..\src\
7. msbuild /m /p:Configuration=Release;Platform=x64 dctl.sln /t:Rebuild

**Our workaround:**
database.hpp: 
std::copy(m_files.begin(), m_files.end(), std::ostream_iterator<std::string>(std::cout, "\n"));
=>
std::copy(m_files.begin(), m_files.end(), std::ostream_iterator<std::wstring, wchar_t>(std::wcout, L"\n"));

**Error info:**
 C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\include\xutility(1784): error C2679: binary '=': no operator found which takes a right-hand operand of type 'std::filesystem::path' (or there is no acceptable conversion)
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\include\iterator(232): note: could be 'std::ostream_iterator<std::string,char,std::char_traits<char>> &std::ostream_iterator<std::string,char,std::char_traits<char>>::operator =(std::ostream_iterator<std::string,char,std::char_traits<char>> &&)'
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\include\iterator(232): note: or       'std::ostream_iterator<std::string,char,std::char_traits<char>> &std::ostream_iterator<std::string,char,std::char_traits<char>>::operator =(const std::ostream_iterator<std::string,char,std::char_traits<char>> &)'
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\include\iterator(208): note: or       'std::ostream_iterator<std::string,char,std::char_traits<char>> &std::ostream_iterator<std::string,char,std::char_traits<char>>::operator =(const _Ty &)'
        with
        [
            _Ty=std::string
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\include\xutility(1784): note: while trying to match the argument list '(std::ostream_iterator<std::string,char,std::char_traits<char>>, std::filesystem::path)'
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\include\xutility(1821): note: see reference to function template instantiation '_OutIt std::_Copy_unchecked<std::filesystem::path*,_Iter>(_InIt,_InIt,_OutIt)' being compiled
        with
        [
            _OutIt=std::ostream_iterator<std::string,char,std::char_traits<char>>,
            _Iter=std::ostream_iterator<std::string,char,std::char_traits<char>>,
            _InIt=std::filesystem::path *
        ]
D:\DCTL\src\include\dctl\egdb\database.hpp(53): note: see reference to function template instantiation '_OutIt std::copy<std::_Vector_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>,std::ostream_iterator<std::string,char,std::char_traits<char>>>(_InIt,_InIt,_OutIt)' being compiled
        with
        [
            _OutIt=std::ostream_iterator<std::string,char,std::char_traits<char>>,
            _Ty=std::filesystem::path,
            _InIt=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<std::filesystem::path>>>
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\include\filesystem(2066): note: see reference to class template instantiation 'std::chrono::time_point<std::filesystem::_File_time_clock,std::filesystem::_File_time_clock::duration>' being compiled
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\include\xstring(1689): note: see reference to class template instantiation 'std::basic_string_view<wchar_t,std::char_traits<wchar_t>>' being compiled

**Comment by rhalbersma** [comment]
Thank you for taking an interest in my library. I have been told by Microsoft that Visual Studio 15.9 Preview 3 should correctly compile and run all unit tests. 

Unfortunately, I haven't access to Visual Studio myself, and I rely on AppVeyor testing for my C++ testing. 

As soon as 15.9 Preview 3 is available (see https://github.com/appveyor/ci/issues/2709) I will re-run the tests and see whether your build errors are still present.

**Comment by StephanTLavavej** [comment]
> I have been told by Microsoft that Visual Studio 15.9 Preview 3 should correctly compile and run all unit tests.

The compiler error here isn't an MSVC issue - it's a platform-specific assumption in this line of code:

https://github.com/rhalbersma/dctl/blob/05c10653fb0c0ae0c89104f2441d8b49727aa713/include/dctl/egdb/database.hpp#L53

This `std::copy()` call is attempting to implicitly convert `std::filesystem::path` to `std::string`, which assumes that the path's string type is narrow. That's true on other platforms, but not on Windows, where the path's string type is `std::wstring`.

To make this code portable, you can call `path::string()` in a loop, although that will convert to the current locale. If you need to preserve Unicode, you'll need more complicated code.

**Comment by rhalbersma** [comment]
@StephanTLavavej To sidestep this entirely, I think the easiest fix is to just use `std::ostream_iterator<std::filesystem::path::string_type>(std::cout, "\n")`

**Comment by QuellaZhang** [comment]
Thank you very much!
@rhalbersma, I have verified on the latest version 95abd6e of DCTL, this issue seems still alive, could you look at this?

[error.txt](https://github.com/rhalbersma/dctl/files/2571272/error.txt)
database.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\include\iterator(209,1): error C2679: binary '<<': no operator found which takes a right-hand operand of type 'const _Ty' (or there is no acceptable conversion)
        with
        [
            _Ty=std::filesystem::path::string_type
        ]
        *_Myostr << _Val;
^
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\include\ostream(438,39): note: could be 'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(std::basic_streambuf<char,std::char_traits<char>> *)'
    basic_ostream& __CLR_OR_THIS_CALL operator<<(_Mysb* _Strbuf) { // insert until end-of-file from a stream buffer

**Comment by rhalbersma** [comment]
@QuellaZhang I don't quite understand the error message here. I'd have to isolate this example for filesystem, it doesn't seem related to any of my own library code. Keeping this issue open for the time being.

**Comment by StephanTLavavej** [comment]
The error is saying that `std::ostream_iterator<std::filesystem::path::string_type>(std::cout, "\n")` is attempting to stream a wide string (on Windows, `path::string_type` is `wstring`) to narrow `cout`.

Here is a possible fix:

```
C:\Temp>type meow.cpp
#include <algorithm>
#include <array>
#include <filesystem>
#include <iostream>
#include <iterator>

int main() {
    const std::array<std::filesystem::path, 3> arr = {{
        R"(C:\cute.txt)",
        R"(D:\fluffy.jpg)",
        R"(E:\kittens.png)"
    }};
    std::ostream_iterator<std::filesystem::path> iter(std::cout, "\n");
    std::copy(arr.begin(), arr.end(), iter);
}

C:\Temp>cl /EHsc /nologo /W4 /MTd /std:c++17 meow.cpp
meow.cpp

C:\Temp>meow
"C:\\cute.txt"
"D:\\fluffy.jpg"
"E:\\kittens.png"
```

**Comment by rhalbersma** [comment]
@StephanTLavavej Thanks, using the `filesystem::path` directly is of course much easier. I think when this code was first created, I still used Boost.FileSystem and later `<experimental/filesystem>`. At some point, gcc or clang didn't accept printing out the `filesystem::path` as template argument for `std::ostream_iterator` but they did implicitly convert to `string`. Can't really know for sure, since I never checked in those failing attempts to print out file names. Hopefully fixed now!

**Comment by QuellaZhang** [comment]
Thank you @rhalbersma . This issue has gone now.
